[package]
name = "rust_image_homework"
version = "0.1.0"
authors = ["Şerafettin Doruk SEZER <sdoruksezer@gmail.com>"]
edition = "2021"

[dependencies]
macroquad = "0.3"
piston_window = "0.118.0"
rand = "0.8"